version: 2

sources:
    - name: jaffle_shop
      description: This is a replica of the Postgres database used by our app
      database: raw
      schema: jaffle_shop
      tables:
      - name: customers
        description: the raw customers data
        columns:
          - name: id
            description: the primary key for raw customer data
            tests:
              - unique
              - not_null
      - name: orders
        description: the raw orders table
        columns:
          - name: id
            description: the primary key for raw orders data
            tests:
              - unique
              - not_null
        loaded_at_field: _etl_loaded_at
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}